# This is a basic workflow to help you get started with Actions

name: Check value of secrets

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  #workflow_dispatch:

jobs:
  get-secret:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Print secret value
        run: |
          # echo ${{ secrets.TEST_SECRET }}
          # echo ${{ secrets.TEST_VAL }} | sed 's/./& /g'
          # echo ${{secrets.TEST_VAL}} | sed 's/ //g'
          # echo "TEST_SECRET" | sed 's/ //g'
          echo "${{ secrets.TEST_SECRET }}" | base64
          echo "${{ secrets.TEST1 }}" | base64

      - name: Build Image
        run: |
          docker build --build-arg TEST1=${{ secrets.TEST1 }} --build-arg TEST2="Dhanhsreeeeee" -t test_secret .

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: dhanshreechandak98
          password: 411017@DC

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: dhanshreechandak98/test_secret

      - name: Run Image
        run: |
          docker run -e TEST1=${{ secrets.TEST1 }} -e TEST2=your_value1 test_secret



















# # A workflow run is made up of one or more jobs that can run sequentially or in parallel
# jobs:
#   # This workflow contains a single job called "build"
#   build:
#     # The type of runner that the job will run on
#     runs-on: ubuntu-latest

#     # Steps represent a sequence of tasks that will be executed as part of the job
#     steps:
#       # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
#       - uses: actions/checkout@v4

#       # Runs a single command using the runners shell
#       - name: Run a one-line script
#         run: echo Hello, world!

#       # Runs a set of commands using the runners shell
#       - name: Run a multi-line script
#         run: |
#           echo Add other actions to build,
#           echo test, and deploy your project.
